[package]
name = "iced-audio-viewer"
version = "0.1.0"
authors = ["Luni-4 <luni-4@hotmail.it>"]
edition = "2018"

[dependencies]
iced = "=0.2.0"

[profile.release]
opt-level = 3
debug = false
lto = true
